name: airport-config-prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - conda-pack=0.4.*
  - conda-build
  - kedro=0.16.2
  - scikit-learn=0.23.2
  - pandas=1.1.*
  - numpy=1.19.*
  - psycopg2=2.8.5
  - matplotlib=3.4.2
  - ipython_genutils=0.2.0
  - pip
  - pip:
      - mlflow==1.19
      - git+https://github.com/nasa/ML-airport-data-services.git
      - xgboost==1.1.1
